#!/usr/bin/env node

var smash = require("./"),
    argv = process.argv;

if (argv[2] === "--list") {
  return void smash.readAllImports(argv.slice(3), function(error, files) {
    if (error) throw error;
    console.log(files.join("\n"));
  });
}

smash(argv.slice(2)).pipe(process.stdout);
